### ISSUE TITLE
Page not present or supervisor privilege Error in Luxmark and Blender

### ISSUE THREAD

**Issue by amartincolby** [ROCm/ROCR-Runtime#119]
I am coming over from my earlier ticket because this problem happens after successful install of the `amdgpu-install` script from the newest 20.50 driver release. I am using the ROCr `--opencl=rocr` option during the all-open `amdgpu-install` script. That is why I am posting this here.

It is listed as having preview support for Ubuntu 20.04.2.

My system
- Ubuntu 20.04.2 kernel 5.8.0-48-generic
- AMD Vega Frontier Edition Air

Both Luxmark and Blender fail with a variation of this error:
```
Mar 28 16:12:45 aaron-desktop blender_blender.desktop[3523]: Memory access fault by GPU node-1 (Agent handle: 0x7f4b9b12d000) on address 0x2c9dd000. Reason: Page not present or supervisor privilege.
```

**Comment by ppanchad-amd** [comment]
@amartincolby Apologies for the lack of response. I am closing the ticket since Vega 10 boards are no longer supported on the latest ROCm 6.2.  If you still encounter issues with Luxmark and Blender with the latest ROCm 6.2, please create a new ticket. Thanks!
