### ISSUE TITLE
Multiple definition of `HSA_VEN_AMD_AQLPROFILE_LEGACY_PM4_PACKET_SIZE'

### ISSUE THREAD

**Issue by mardom1** [ROCm/ROCR-Runtime#121]
I am trying to use the Rocprofiler library in a project, but if the header is included in multiple source files, the linker throws the following error:

```
multiple definition of `HSA_VEN_AMD_AQLPROFILE_LEGACY_PM4_PACKET_SIZE'
```

I tracked the problem down to this line in the `hsa_ven_amd_aqlprofile.h` header file from HSA:

https://github.com/RadeonOpenCompute/ROCR-Runtime/blob/ea47a79081e0293a5256b7fb908941c3ffb38468/src/inc/hsa_ven_amd_aqlprofile.h#L230

When included in two source files, the same definition appears twice, which the linker cannot handle.

If I am not including the library wrong, a possible fix could be to make it an external declaration and define it in one source file, or to make the definition static.

Best regards,
Marcel

**Comment by ppanchad-amd** [comment]
@mardom1 Apologies for the lack of response.  Can you please check if this issue still occurs with the latest ROCm 6.2? If not, please close the ticket. Thanks!

**Comment by tcgu-amd** [comment]
@mardom1, @ppanchad-amd. I was able to reproduce the issue on ROCm-6.2.

**Comment by tcgu-amd** [comment]
@mardom1 @ppanchad-amd I was able to reproduce the issue on 6.2. Currently investigating the issue internally. There is a reproducer of the issue linked here https://github.com/ROCm/rocprofiler/issues/114.

**Comment by tcgu-amd** [comment]
Created pull request for tracking the change: https://github.com/ROCm/ROCR-Runtime/pull/230

**Comment by tcgu-amd** [comment]
@mardom1 The correct usage of the header file would be that instead of '#include <rocprofiler.h>', use  '#include <v2/rocprofiler.h>' instead. 

Please refer to the documentation for the API here:
 https://github.com/ROCm/rocprofiler?tab=readme-ov-file#rocprofiler-v1

Along with the example here:
[ROCProfilerV2 API — rocprofiler 2.0.0 Documentation (amd.com)](https://rocm.docs.amd.com/projects/rocprofiler/en/latest/reference/rocprofilerv2-api.html#kernel-profiling-1)

Apologies for the confusion. Hope this helps!

**Comment by tcgu-amd** [comment]
@mardom1 This seems to be a known issue unfortunately. To circumvent it, please trying using v2 API from the documentation here 
[GitHub - ROCm/rocprofiler: ROC profiler library. Profiling with perf-counters and derived metrics.](https://github.com/ROCm/rocprofiler?tab=readme-ov-file#rocprofiler-v1)
 
Along with the example here:
[ROCProfilerV2 API — rocprofiler 2.0.0 Documentation (amd.com)](https://rocm.docs.amd.com/projects/rocprofiler/en/latest/reference/rocprofilerv2-api.html#kernel-profiling-1)

Thank you!
