### ISSUE TITLE
hsa_amd_pointer_info doesn't work when calling from a function?

### ISSUE THREAD

**Issue by ye-luo** [ROCm/ROCR-Runtime#128]
On my machine, I got `hsa_amd_pointer_info failed`.
If I change `if(0)` to ` if(1)`, the call succeeds.

reproducer.
```
#include <hsa/hsa.h>
#include <hsa/hsa_ext_amd.h>
#include <stdio.h>

#define N 100293

int checkLocked(void *ptr) {
  hsa_amd_pointer_info_t info;
  hsa_status_t herr = HSA_STATUS_SUCCESS;

  herr = hsa_amd_pointer_info(ptr, &info, NULL, NULL, NULL);
  if (herr != HSA_STATUS_SUCCESS) {
    printf("  hsa_amd_pointer_info failed %d\n", herr);
    return 1;
  }

  if (info.type != HSA_EXT_POINTER_TYPE_LOCKED) {
    printf("  pointer is noooooooooooot locked\n");
    return 1;
  } else
    printf("  pointer is locked func\n");

  return 0;
}

int main() {
  hsa_status_t herr = hsa_init();
  if (herr != HSA_STATUS_SUCCESS) {
    printf("hsa_init failed\n");
    return 1;
  }

  const int n = N;
  int *a = new int[n];
  for (int i = 0; i < n; i++)
    a[i] = 0;

  checkLocked(a);

  int *a_locked = nullptr;
  herr = hsa_amd_memory_lock(a, n * sizeof(int), nullptr, 0, (void **)&a_locked);
  if (herr != HSA_STATUS_SUCCESS) {
    printf("Locking failed\n");
    return 1;
  }

  if(0)
  {
    hsa_amd_pointer_info_t info;
    herr = hsa_amd_pointer_info(a, &info, NULL, NULL, NULL);
    if (herr != HSA_STATUS_SUCCESS) {
      printf("  hsa_amd_pointer_info failed\n");
      return 1;
    }

    if (info.type != HSA_EXT_POINTER_TYPE_LOCKED) {
      printf("  pointer is noooooooooooot locked\n");
      return 1;
    } else
      printf("  pointer is locked main\n");
  }
  else
    checkLocked(a);

  hsa_shut_down();
  return herr;
}

```

**Comment by JonChesterfield** [comment]
That's weird. I see the void* vs int* type on the pointer, and the indirection through a function call, but hsa_amd_pointer_info is in a shared library (so abi is fixed), can't imagine why this would matter. Will see if it reproduces locally.

**Comment by ye-luo** [comment]
I updated a bit the above code
```
yeluo@epyc-server:~$ clang++ -O0 -I/opt/rocm-4.5.2/include test_hsa.cpp -L/opt/rocm-4.5.2/lib -lhsa-runtime64 && ./a.out 
  pointer is noooooooooooot locked
  hsa_amd_pointer_info failed 4097
yeluo@epyc-server:~$ clang++ -O1 -I/opt/rocm-4.5.2/include test_hsa.cpp -L/opt/rocm-4.5.2/lib -lhsa-runtime64 && ./a.out 
  pointer is noooooooooooot locked
  pointer is locked func
yeluo@epyc-server:~$ clang++ -O3 -I/opt/rocm-4.5.2/include test_hsa.cpp -L/opt/rocm-4.5.2/lib -lhsa-runtime64 && ./a.out 
  pointer is noooooooooooot locked
  pointer is locked func
```
So It seems to be a real issue at "-O0"

**Comment by ye-luo** [comment]
upstream clang and AOMP clang don't matter. g++ constantly failed.
```
yeluo@epyc-server:~$ g++ -O0 -I/opt/rocm-4.5.2/include test_hsa.cpp -L/opt/rocm-4.5.2/lib -lhsa-runtime64 && ./a.out 
  pointer is noooooooooooot locked
  hsa_amd_pointer_info failed 4097
yeluo@epyc-server:~$ g++ -O1 -I/opt/rocm-4.5.2/include test_hsa.cpp -L/opt/rocm-4.5.2/lib -lhsa-runtime64 && ./a.out 
  pointer is noooooooooooot locked
  hsa_amd_pointer_info failed 4097
yeluo@epyc-server:~$ g++ -O3 -I/opt/rocm-4.5.2/include test_hsa.cpp -L/opt/rocm-4.5.2/lib -lhsa-runtime64 && ./a.out 
  pointer is noooooooooooot locked
  hsa_amd_pointer_info failed 4097
```

**Comment by fxkamd** [comment]
What if you change if(0) to if(!a_locked)? That way the compiler would be forced to run hsa_amd_memory_lock before checkLocked(a). Without that, it doesn't know that the checkLocked call depends on hsa_amd_memory_lock.

**Comment by ye-luo** [comment]
> What if you change if(0) to if(!a_locked)? That way the compiler would be forced to run hsa_amd_memory_lock before checkLocked(a). Without that, it doesn't know that the checkLocked call depends on hsa_amd_memory_lock.

It doesn't change the above behavior.

**Comment by JonChesterfield** [comment]
hsa_amd_memory_lock and hsa_amd_pointer_info are both calls to unknown functions in a shared library - the C++ compiler has to pessimistically assume they might mutate the same global state so can't reorder them. Though different behaviour on O0 and O1 does support the x64 compiler bug theory. Sadly this still doesn't reproduce for me, not sure where the config difference lies

**Comment by schung-amd** [comment]
Hi @ye-luo, are you still having this issue? I was able to reproduce the discrepancy between the function and inline versions as well as the discrepancy between -O0 and-O1. The documentation at https://github.com/ROCm/ROCR-Runtime/blob/d614ea8bbd73a7832c265725117274d13041ff06/src/inc/hsa_ext_amd.h#L2020 states that info.size must be "Set to sizeof(hsa_amd_pointer_t) prior to calling
  hsa_amd_pointer_info". Without doing this, the size field is uninitialized, leading to UB. On my repro, with -O0, this consistently results in a size of 0 when the second call is inside the function, and a size of 2 when it is inlined. https://github.com/ROCm/ROCR-Runtime/blob/d614ea8bbd73a7832c265725117274d13041ff06/src/core/runtime/runtime.cpp#L870 checks for a size of 0 to test if the size is uninitialized, so this fails only for the specific in-function case even though all of these values are uninitialized and should fail. Notably, when -O1 is passed, the uninitialized size fields contain random values, so this check is not tripped, which explains your observations on -O1 and higher.

Therefore, to address your issue, set `info.size` to `sizeof(hsa_amd_pointer_t)` before calling `hsa_amd_pointer_info`. On my local repro this code actually does not work properly even with the size field set, as it appears to be failing to lock the pointer, but I suspect this failure is unrelated.

**Comment by ye-luo** [comment]
@schung-amd thank you for pointing out the issue in my code. After setting the info.size, I got consistent behaviors.
