### ISSUE TITLE
Implement timeout in case of unresponsive GPU

### ISSUE THREAD

**Issue by v01dXYZ** [ROCm/ROCR-Runtime#138]
Some faulty kernels can cause the GPU to act not as expected by the runtime (such as answering in a reasonable amount of time).

Currently, the runtime will loop until the GPU responds: 

https://github.com/RadeonOpenCompute/ROCR-Runtime/blob/c5f95f9b33af2aa1dd1e6ba76b18cd2e291f3c7d/src/core/runtime/amd_aql_queue.cpp#L930

**Comment by v01dXYZ** [comment]
This is related to https://github.com/RadeonOpenCompute/ROCR-Runtime/issues/96 (infinite loop in `ExecutePM4`).

**Comment by v01dXYZ** [comment]
Thank you for your answer, it is very much appreciated.

My suggestion seems a little bit silly when taking into account your informed point of view.

The context of this infinite loop behaviour is the following: It seemed that `s_call_b64` using an unavailable register pair leads to a GPU hang.

Just to emphasis:
```
#1 amd::AqlQueue::ExecutePM4(...)
#2 amd::GpuAgent::InvalidateCodeCaches()
#3  amd::LoaderContext::SegmentAlloc(...)
#4 amd::hsa::loader::ExecutableImpl::LoadSegmentsV2(...)
#5 amd::hsa::loader::ExecutableImpl::LoadSegments(...)
#6 amd::hsa::loader::ExecutableImpl::LoadCodeObject(...
#7  HSA::hsa_executable_load_agent_code_object(...)
^^^^ ROCr ^^^^
#8  roc::LightningProgram::setKernels(...) () from /opt/rocm-3.5.1/hip/lib/libamdhip64.so.3
#9  device::Program::linkImplLC(...) () from /opt/rocm-3.5.1/hip/lib/libamdhip64.so.3
#10 device::Program::build(...) () from /opt/rocm-3.5.1/hip/lib/libamdhip64.so.3
#11 amd::Program::build(...) ()
   from /opt/rocm-3.5.1/hip/lib/libamdhip64.so.3
^^^ ROCclr ^^^ 
#12 PlatformState::getFunc(...) () from /opt/rocm-3.5.1/hip/lib/libamdhip64.so.3
#13 hipLaunchKernel () from /opt/rocm-3.5.1/hip/lib/libamdhip64.so.3
^^^ hipamd ^^^
```

Other remarks:
* `ExecutePM4` could only be accessed by calling `LoadCodeObject`
* `LoadCodeObject` is only called in `hsa_executable_load_program_code_object` (and in an other deprecated function)

I am not familiar with the data structure of ROCr, but it doesn't seem it is related to a user apparent lock. It is internal to ROCr that is waiting for the Invalid Cache PM4 packet to be processed, which never happens, causing the user application to stall.

What can we do to avoid the user to turn perplexed ? Is that a good idea to print some log every now and then to let the user detect it ?

**Comment by fxkamd** [comment]
Probably ROCr isn't handling the HW_EXCEPTION events KFD sends to notify it of the GPU reset.

**Comment by ppanchad-amd** [comment]
@v01dXYZ Do you still need assistance with this ticket? If not, please close the ticket. Thanks!

**Comment by ppanchad-amd** [comment]
@v01dXYZ Closing ticket.  Please feel free to re-open ticket if you still need assistance with this ticket. Thanks!
