### ISSUE TITLE
Unitialised Segment objects: defect or feature 

### ISSUE THREAD

**Issue by v01dXYZ** [ROCm/ROCR-Runtime#139]
This code appends new segments to the elf image. But those segments need to be initialised using `pull`. Does the intent of the code is to do that ? If it is, that's not what it does, as the vector is likely not empty at this stage.

https://github.com/RadeonOpenCompute/ROCR-Runtime/blob/45e6039881b606bc04fedbfed41f9e9ef21d43cf/src/libamdhsacode/amd_elf_image.cpp#L1444-L1445

**Comment by ppanchad-amd** [comment]
@v01dXYZ Apologies for the lack of response.  Do you still need assistance with this ticket? If not, please close the ticket. Thanks!

**Comment by ppanchad-amd** [comment]
@v01dXYZ Closing ticket.  Please feel free to re-open ticket if you still need assistance? Thanks!
