### ISSUE TITLE
``hsa_executable_load_program_code_object`` could not succeed

### ISSUE THREAD

**Issue by v01dXYZ** [ROCm/ROCR-Runtime#140]
By looking at the code, ``hsa_executable_load_program_code_object`` is equivalent to ``hsa_executable_load_agent_code_object`` with `agent := {0}`.

This could not succeed as it seems the code calls `hsa_agent_get_info` with the handle. It fails since the handle is not valid (internally it is actually a pointer).

`hsa_agent_get_info` is called here:
https://github.com/RadeonOpenCompute/ROCR-Runtime/blob/45e6039881b606bc04fedbfed41f9e9ef21d43cf/src/core/runtime/amd_loader_context.cpp#L435-L436
This induces a `OUT_OF_RESOURCES` error status:
https://github.com/RadeonOpenCompute/ROCR-Runtime/blob/45e6039881b606bc04fedbfed41f9e9ef21d43cf/src/loader/executable.cpp#L1325-L1327

**Comment by ppanchad-amd** [comment]
@v01dXYZ Apologies for the lack of response.  Can you please check if this issue still occurs with the latest ROCm 6.2? If not, please close the ticket. Thanks!

**Comment by ppanchad-amd** [comment]
@v01dXYZ Closing ticket.  Please feel free to re-open ticket if you still need assistance. Thank!
