### ISSUE TITLE
Segfault on lbhsa-runtime64 5.4.1-2 with KoboldAI on rx580

### ISSUE THREAD

**Issue by TanyaEleventhGoddess** [ROCm/ROCR-Runtime#150]
In conjunction with KoboldAI, libhsa 5.4.1-2 seems to crash with settings requiring more VRAM space.
If a model is fully loaded in the GPU's dedicated VRAM it doesn't segfault, if the model is fully loaded in the machine's RAM memory it doesn't segfault either. If settings are half and half, it segfaults resulting in the following dmesg output:

`[Fri Dec 30 10:49:51 2022]
python[3138146]: segfault at 1 ip 00007f447cecde86 sp 00007ffca1d199c0 error 4 in libhsa-runtime64.so[7f447ce00000+131000]`

**Comment by dayatsin-amd** [comment]
Can you please provide instructions on how to reproduce?

**Comment by TanyaEleventhGoddess** [comment]
Install KoboldAI, download any model and load it in VRAM, if even a byte is loaded in VRAM it will mercilessly crash

**Comment by ppanchad-amd** [comment]
@TanyaEleventhGoddess Apologies for the lack of response. Can you please check if your issue still exists with the latest ROCm 6.2? If not, please close the ticket. Thanks!

**Comment by ppanchad-amd** [comment]
@TanyaEleventhGoddess Closing ticket.  Please feel free to re-open ticket if you still need assistance with your issue. Thanks!
