### ISSUE TITLE
Please adopt actual open-source development model; instead of "throw the source over the wall"

### ISSUE THREAD

**Issue by preda** [ROCm/ROCR-Runtime#188]
In the open spirit of ROCm, please start developing ROCR-Runtime in the open. Publish the commits to the public repository as they happen. 

Right now I see seldom (about every 3 months) code drops squashed into huge single commits. That's not open-source development, that's closed-source development with periodic source drops. As an example see this commit with 45 changed files with 3,286 additions and 539 deletions:

https://github.com/ROCm/ROCR-Runtime/commit/22dc4638862c0cd4ab454eef720e6a29e3d1d9a5

Another example, the binary code available right now as part of ROCm 6.1RC (libhsa-runtime64.so.1.13.60100) is ahead of the source code presented in the ROCR-Runtime repository. If I want to debug the binary, I don't have access to the source. That's not open-source.

**Comment by dayatsin-amd** [comment]
Hi @preda,
We are currently working on fixing the public ROCR-Runtime repository layout and history so that it is a mirror copy of our internal repository. We are hoping to have full git logs published within the ROCm-6.3 - ROCm-6.4 timeframe.
Sorry for the inconvenience.

**Comment by preda** [comment]
@dayatsin-amd Thank you for the feedback, and I'm happy to hear that!
