### ISSUE TITLE
Failure to load binary image ... Error in hsa_executable_load_code_object: HSA_STATUS_ERROR_INCOMPATIBLE_ARGUMENTS: The arguments passed to a functions are not compatible.

### ISSUE THREAD

**Issue by woodard** [ROCm/ROCR-Runtime#198]
### Problem Description

This problem actually happens on ROCm 6.1 but that was not available in the dropdown list.

When I try to compile for both the GFX906 and the GFX1100 it looks like the runtime tries to load the wrong GPU code in many cases.

[ben@darkstar Audit]$ make clean
rm -rf *.o *.x
[ben@darkstar Audit]$ make ARCH=gfx906 CC=/opt/rocm-6.1.0/bin/amdclang++
ARCH = gfx906
/opt/rocm-6.1.0/bin/amdclang++ -g -O2 -fopenmp --offload-arch=gfx906 ddot.c -O2 -o ddot.amdclang++.x
clang++: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
[ben@darkstar Audit]$ ./ddot.amdclang++.x
Input vector length N:
20
Using N = 20
Success! Result = 4.940000e+03
Initialization took    0.000 seconds.
Computation took    0.000 seconds.

[ben@darkstar Audit]$ make ARCH=gfx1100 CC=/opt/rocm-6.1.0/bin/amdclang++
ARCH = gfx1100
/opt/rocm-6.1.0/bin/amdclang++ -g -O2 -fopenmp --offload-arch=gfx1100 ddot.c -O2 -o ddot.amdclang++.x
clang++: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
[ben@darkstar Audit]$ ./ddot.amdclang++.x
Input vector length N:
20
Using N = 20
"PluginInterface" error: Failure to load binary image 0x13d46e0 on device 0: Error in hsa_executable_load_code_object: HSA_STATUS_ERROR_INCOMPATIBLE_ARGUMENTS: The arguments passed to a functions are not compatible.
Libomptarget error: Unable to generate entries table for device id 0.
Libomptarget error: Failed to init globals on device 0
Libomptarget error: Consult https://openmp.llvm.org/design/Runtimes.html for debugging options.
ddot.c:32:3: Libomptarget fatal error 1: failure of target construct while offloading is mandatory
Aborted (core dumped)

The same thing happens with 
ARCH=gfx1100,gfx906 fails

ARCH=gfx906,gfx1100

I haven't fully debugged the problem but it seems like the logic to select the code segment for the GPU gets confused when there are two different GPUs installed.

I found old bug reports of people having a similar problem all the way back to ROCm 1.0 when they had mixed GPU cards.

I believe that this is ultimately an important testcase to support.  What we would like to get to is a place where a user may have an APU and a dGPU and then they startup a small workload and run into problems rather than having both units working on it.

### Operating System

NAME="Red Hat Enterprise Linux" VERSION="9.3 (Plow)"

### CPU

model name      : AMD Ryzen Threadripper PRO 5955WX 16-Cores

### GPU

AMD Radeon Pro VII, AMD Radeon RX 7900 XTX

### ROCm Version

ROCm 6.0.0

### ROCm Component

ROCR-Runtime

### Steps to Reproduce

See above, this seems to happen with at least several little test programs that I have tried. There is not really anything special in ddot.c

### (Optional for Linux users) Output of /opt/rocm/bin/rocminfo --support

[ben@darkstar try1]$ /opt/rocm/bin/rocminfo --support
ROCk module version 6.3.6 is loaded
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.13
Runtime Ext Version:     1.4
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             
Mwaitx:                  DISABLED
DMAbuf Support:          YES

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    AMD Ryzen Threadripper PRO 5955WX 16-Cores
  Uuid:                    CPU-XX                             
  Marketing Name:          AMD Ryzen Threadripper PRO 5955WX 16-Cores
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   4000                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            32                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    131192084(0x7d1d514) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    131192084(0x7d1d514) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    131192084(0x7d1d514) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*******                  
Agent 2                  
*******                  
  Name:                    gfx906                             
  Uuid:                    GPU-ac4210e173c71c04               
  Marketing Name:          AMD Radeon (TM) Pro VII            
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16(0x10) KB                        
    L2:                      8192(0x2000) KB                    
  Chip ID:                 26273(0x66a1)                      
  ASIC Revision:           1(0x1)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   1700                               
  BDFID:                   25344                              
  Internal Node ID:        1                                  
  Compute Unit:            60                                 
  SIMDs per CU:            4                                  
  Shader Engines:          4                                  
  Shader Arrs. per Eng.:   1                                  
  WatchPts on Addr. Ranges:4                                  
  Coherent Host Access:    FALSE                              
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      TRUE                               
  Wavefront Size:          64(0x40)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        40(0x28)                           
  Max Work-item Per CU:    2560(0xa00)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Packet Processor uCode:: 469                                
  SDMA engine uCode::      145                                
  IOMMU Support::          None                               
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    16760832(0xffc000) KB              
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    16760832(0xffc000) KB              
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 3                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Recommended Granule:0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx906:sramecc+:xnack-
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*******                  
Agent 3                  
*******                  
  Name:                    gfx1100                            
  Uuid:                    GPU-32718d9ad8c12635               
  Marketing Name:          Radeon RX 7900 XTX                 
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    2                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      32(0x20) KB                        
    L2:                      6144(0x1800) KB                    
    L3:                      98304(0x18000) KB                  
  Chip ID:                 29772(0x744c)                      
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   2304                               
  BDFID:                   17152                              
  Internal Node ID:        2                                  
  Compute Unit:            96                                 
  SIMDs per CU:            2                                  
  Shader Engines:          6                                  
  Shader Arrs. per Eng.:   2                                  
  WatchPts on Addr. Ranges:4                                  
  Coherent Host Access:    FALSE                              
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      TRUE                               
  Wavefront Size:          32(0x20)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        32(0x20)                           
  Max Work-item Per CU:    1024(0x400)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Packet Processor uCode:: 550                                
  SDMA engine uCode::      19                                 
  IOMMU Support::          None                               
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    25149440(0x17fc000) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    25149440(0x17fc000) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 3                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Recommended Granule:0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx1100         
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*** Done ***

**Comment by dayatsin-amd** [comment]
Hi Ben,
I have not looked at the ddot.c application, but if the ddot.c application is always trying to load on the first GPU, then this might cause this problem.

Can you try to use ROCR_VISIBLE_DEVICES mask the GPU that does not have the ARCH support compiled in.

To only expose the first GPU (gfx906 in your case) to the application:
ROCR_VISIBLE_DEVICES=0

To only expose the secon GPU (gfx1100 in your case) to the application:
ROCR_VISIBLE_DEVICES=1

**Comment by woodard** [comment]
That appears to have worked.  This is just a short test code that a user gave me. Is there some line in the code that I should change to make this always work? Something I should have in a "best practices FAQ". In other words, what line should I look for in the code to change. (I'm happy to share the trivial test program if it would help).

[ben@darkstar ddot]$ make ARCH=gfx906,gfx1100 CC=/opt/rocm-6.1.0/bin/amdclang
ARCH = gfx906,gfx1100
/opt/rocm-6.1.0/bin/amdclang -g -O2 -fopenmp --offload-arch=gfx906,gfx1100 ddot.c -O2 -o ddot.amdclang.x
[ben@darkstar ddot]$ ./ddot.amdclang.x
Input vector length N:
20
Using N = 20
"PluginInterface" error: Failure to load binary image 0x10b46f0 on device 0: Error in hsa_executable_load_code_object: HSA_STATUS_ERROR_INCOMPATIBLE_ARGUMENTS: The arguments passed to a functions are not compatible.
Libomptarget error: Unable to generate entries table for device id 0.
Libomptarget error: Failed to init globals on device 0
Libomptarget error: Consult https://openmp.llvm.org/design/Runtimes.html for debugging options.
ddot.c:32:3: Libomptarget fatal error 1: failure of target construct while offloading is mandatory
Aborted (core dumped)
[ben@darkstar ddot]$ ROCR_VISIBLE_DEVICES=0 !!
ROCR_VISIBLE_DEVICES=0 ./ddot.amdclang.x
Input vector length N:
20
Using N = 20
Success! Result = 4.940000e+03
Initialization took    0.000 seconds.
Computation took    0.000 seconds.
[ben@darkstar ddot]$ ROCR_VISIBLE_DEVICES=1 ./ddot.amdclang.x
Input vector length N:
20
Using N = 20
Success! Result = 4.940000e+03
Initialization took    0.000 seconds.
Computation took    0.000 seconds.

**Comment by woodard** [comment]
[ddot.tar.gz](https://github.com/ROCm/ROCR-Runtime/files/15065284/ddot.tar.gz)

**Comment by dayatsin-amd** [comment]
Hi Ben,
The hsa_agent_iterate_isas API can be used to determine the gfx version of a GPU:
https://github.com/ROCm/ROCR-Runtime/blob/master/src/inc/hsa.h#L3619

You can see the example of how the rocminfo utility is extracting the ISA name string here:
https://github.com/ROCm/rocminfo/blob/master/rocminfo.cc#L1020
https://github.com/ROCm/rocminfo/blob/master/rocminfo.cc#L787

The ISA name string will be "gfx906", "gfx1100"

And then the application can be modified to check whether the ISA for a specific GPU agent has been compiled in and skip that agent otherwise.

**Comment by woodard** [comment]
This should probably get moved to AMD's OpenMP clang implementation then. I looked at the code provided me by the user and it is not HSA code at all all the GPU code is generated indirectly by:

`#pragma omp target teams distribute parallel for shared(vecA, vecB) reduction(+:result)`

and

`#pragma omp target exit data map(delete: vecA, vecB) map(from: result)`

I'll see if I can figure out how to move the issue, Otherwise, I will closse the issue here and open a new one over in ROCm clang.

**Comment by woodard** [comment]
I believe that this problem is better handled by the ROCm AOMP project. I'm going to close this issue here and then file it over there.
