### ISSUE TITLE
rocr builds using clang/llvm found lying around on the host system, e.g. one that doesn't know what the targets are

### ISSUE THREAD

**Issue by JonChesterfield** [ROCm/ROCR-Runtime#221]
### Problem Description

Nested deep within the rocr cmake are lines like `find_package(Clang REQUIRED HINTS ${CMAKE_PREFIX_PATH}/llvm PATHS /opt/rocm/llvm )`

https://github.com/ROCm/ROCR-Runtime/blob/3ca6209de17a63d1c949852a314a99a3ff809e6e/src/core/runtime/blit_shaders/CMakeLists.txt#L48 

https://github.com/ROCm/ROCR-Runtime/blob/3ca6209de17a63d1c949852a314a99a3ff809e6e/src/core/runtime/trap_handler/CMakeLists.txt#L46

If the clang/llvm that finds is different to the one the user is hoping to build things with, if they're lucky, they get a hard failure. I've discovered this from "clang-16 error: invalid target ID 'gfx941'". It's supposed to be building using the compiler specified by the aomp build scripts, which do know how to build that target.

This is a serious failure mode. Old llvm versions aren't especially likely to compile the shaders correctly and broken trap handlers will be very confusing. People building rocm or aomp really want to use the clang from that project, not whatever was on the path. I am lucky that this stumbled across a hard error instead of just miscompiling it.

This is probably why the HSA I build from source does not work and hasn't since rocm 5.2. I always have clang on the path and I don't install rocm under /opt.

### Operating System

Ubuntu

### CPU

NA 

### GPU

Other

### ROCm Version

ROCm 6.0.0

### ROCm Component

ROCR-Runtime

### Steps to Reproduce

Build rocr with clang-16 on the path, falls over. Hazard introduced with rocm 5.3.

**Comment by darren-amd** [comment]
Hi @JonChesterfield,

You can manually specify the path you would like the build script to look for Clang by providing the path in the environment variable `CMAKE_PREFIX_PATH`. This can be done by passing in the flag `-DCMAKE_PREFIX_PATH=/path/to/llvm` when calling CMake. Give that a try and let me know if you run into any issues, thanks!
