### ISSUE TITLE
[Issue]:   `INSTALL_PREFIX is a marker for install(EXPORT) only.  It should never be   evaluated.`

### ISSUE THREAD

**Issue by makslevental** [ROCm/ROCR-Runtime#234]
### Problem Description

This broke us over at https://github.com/nod-ai/ROCR-Runtime:

https://github.com/ROCm/ROCR-Runtime/blob/amd-staging/runtime/hsa-runtime/CMakeLists.txt#L330

```CMake
  target_link_libraries ( ${CORE_RUNTIME_NAME} INTERFACE -Wl,$<INSTALL_PREFIX>/${CMAKE_INSTALL_LIBDIR}/cmake/${CORE_RUNTIME_NAME}/${LNKSCR}
    -Wl,--whole-archive $<TARGET_FILE:${CORE_RUNTIME_NAME}::${CORE_RUNTIME_TARGET}> -Wl,--no-whole-archive)
```

on CMake 3.30 produces

```
CMake Error at runtime/hsa-runtime/CMakeLists.txt:330 (target_link_libraries):
  Error evaluating generator expression:

    $<INSTALL_PREFIX>

  INSTALL_PREFIX is a marker for install(EXPORT) only.  It should never be
  evaluated.
```

which I believe is reasonable since you can't link against something in the `INSTALL_PREFIX`. Possibly this is meant to function like updating the RPATH?

cc @atgutier @eddierichter-amd @ypapadop-amd

**Comment by ppanchad-amd** [comment]
Hi @makslevental. Internal ticket has been created to investigate your issue. Thanks!

**Comment by taylding-amd** [comment]
Hi @makslevental, I could not reproduce the error, would you share your build script and provide more information about your environment?

**Comment by makslevental** [comment]
> Hi @makslevental, I could not reproduce the error, would you share your build script and provide more information about your environment?

Just do `BUILD_SHARED_LIBS=OFF` and it'll break.

**Comment by taylding-amd** [comment]
Hi @makslevental, I tried building both the ROCm/ROCR-Runtime and nod-ai/ROCR-Runtime repositories, but I was unable to reproduce the error with BUILD_SHARED_LIBS=OFF. If you message me on Teams, I can share my environment with you for your reference.

**Comment by taylding-amd** [comment]
Hi, this issue will be closed now due to inactivity. Please feel free to reopen it or ask follow-up questions should further assistance be required. Thanks!
