### ISSUE TITLE
Should this project return R9 390 as gfx702?

### ISSUE THREAD

**Issue by Lucretia** [ROCm/ROCR-Runtime#74]
Similar issue to https://github.com/RadeonOpenCompute/ROCm/issues/891 - again, I can send a patch if required.

**Comment by Lucretia** [comment]
@skeelyamd @fxkamd - any chance of an answer to this query?

**Comment by ppanchad-amd** [comment]
@Lucretia Apologies for the lack of response.  GFX 702 is no longer supported on our latest ROCm 6.2. Thanks!
