### ISSUE TITLE
warning: the use of `tempnam' is dangerous, better use `mkstemp'

### ISSUE THREAD

**Issue by PhilipDeegan** [ROCm/ROCR-Runtime#95]
https://github.com/RadeonOpenCompute/ROCR-Runtime/blob/0d9576a5cba4ca4bd17bd2a4a744e59151fcdf9c/src/libamdhsacode/amd_hsa_code_util.cpp#L962

**Comment by ppanchad-amd** [comment]
@PhilipDeegan Apologies for the lack of response. Internal ticket has been created to fix this. Thanks!

**Comment by darren-amd** [comment]
Hi @PhilipDeegan,

Thanks for the suggestion! This has since been implemented here: [mkstemp change](https://github.com/ROCm/ROCR-Runtime/commit/e82025bffa693d8b533018260579958bd63dd124) to use mkstemp instead of tempnam. Thanks!
